export const flag = [
    {
        id:1,
        imgSrc:'https://readymadeui.com/usa_flag.webp',
        imgAlt:'USA',
        title:'USA'
    },
    {
        id:2,
        imgSrc:'https://readymadeui.com/uk_flag.webp',
        imgAlt:'England',
        title:'England'
    },
    {
        id:3,
        imgSrc:'https://readymadeui.com/singapore_flag.webp',
        imgAlt:'Singapore',
        title:'Singapore'
    },
    {
        id:4,
        imgSrc:'https://readymadeui.com/india_flag.webp',
        imgAlt:'India',
        title:'India'
    },
]