const products = [
    {
      id: 1,
      categoryName:`Men's Apparel`,
      name: 'Basic Tee',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Basic Tee in black.",
      price: '$35',
      color: 'Black',
      sold: '10k+',
      star: 4.95,
      badge:'Sulit Deal'
    },
    {
      id: 2,
      categoryName:`Men's Apparel`,
      name: 'Dri-Fit',
      href: '#',
      imageSrc: 'https://img.lazcdn.com/g/p/9ff06a8b96b56c3695f91ddccda5a5c4.png_720x720q80.png',
      imageAlt: "UNISEX",
      price: '$20',
      color: 'Red',
      sold: '5.5k+',
      star: 4.2,
      badge:'Sulit Deal'
    },
    {
      id: 3,
      categoryName:`Men's Apparel`,
      name: 'Basic Tee',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Basic Tee in black.",
      price: '$35',
      color: 'Black',
      sold: '90',
      star: 2,
      badge:''
    },
    {
      id: 4,
      categoryName:`Men's Apparel`,
      name: 'Basic Tee',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Basic Tee in black.",
      price: '$35',
      color: 'Black',
      sold: '8',
      star: 1,
      badge:''
    },
    {
      id: 5,
      categoryName:`Men's Apparel`,
      name: 'Basic Tee',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Basic Tee in black.",
      price: '$35',
      color: 'Black',
      sold: '11.2k+',
      star: 4.95,
      badge:'Sulit Deal'
    },
    {
      id: 6,
      categoryName:`Men's Apparel`,
      name: 'Basic Tee',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Basic Tee in black.",
      price: '$35',
      color: 'Black',
      sold: '888',
      star: 3.85,
      badge:''
    },
    {
      id: 7,
      categoryName:`Men's Apparel`,
      name: 'Basic Tee',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Basic Tee in black.",
      price: '$35',
      color: 'Black',
      sold: '307',
      star: 2.95,
      badge:''
    },
    {
      id: 8,
      categoryName:`Men's Apparel`,
      name: 'Basic Tee',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Basic Tee in black.",
      price: '$35',
      color: 'Black',
      sold: '455',
      star: 4.10,
      badge:''
    },
  {
      id: 9,
      categoryName:`Men's Apparel`,
      name: 'Basic Tee',
      href: '#',
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-page-01-related-product-01.jpg',
      imageAlt: "Front of men's Basic Tee in black.",
      price: '$35',
      color: 'Black',
      sold: '999',
      star: 3.50,
      badge:'Sulit Deal'
    },
    // More products...
  ]
  export default products